### ISSUE TITLE
Colorpicker

### ISSUE THREAD

**Issue by Arthur1967** [kittmaster/skin.madnox#4]
Needs to be updated. I found it in another repository and now I no longer get an error. Just letting you know.

**Comment by kittmaster** [comment]
It should auto update, from the script source. But I don't see it calling home either. Where did you find it? I also have a post on the forums that fixes the out of the box issue if you are starting from scratch with it.

**Comment by Arthur1967** [comment]
I have the diggz repo and as soon as you install it just the repo and hit automatic updates It’s color picker updates and then I take out diggz

**Comment by Arthur1967** [comment]
http://diggz1.me/diggzrepo
